"""add_movies_table

Revision ID: 26ccb64fa5c6
Revises: f567ece18f12
Create Date: 2024-09-17 03:03:25.436540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ccb64fa5c6'
down_revision: Union[str, None] = 'f567ece18f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('poster', sa.String(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_uuid'), 'movies', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_uuid'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
