"""add_seats_table

Revision ID: aa9de0041c49
Revises: 51c0a7ce6272
Create Date: 2024-12-10 14:47:28.965496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9de0041c49'
down_revision: Union[str, None] = '51c0a7ce6272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.Column('reserved', sa.Boolean(), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_uuid'), 'seats', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seats_uuid'), table_name='seats')
    op.drop_table('seats')
    # ### end Alembic commands ###
